services:
  - type: web
    name: nova-luxury-furnishings-backend
    env: node
    plan: standard
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MODE
        value: production
      - key: JWT_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: baseURL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: EMAIL_NAME
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
    rootDir: backend
